ROOT_PATH: /home/benjamin.cretois/data/esc50/
AUDIO_DIR_ESC50: /home/benjamin.cretois/data/esc50/ESC-50-master/audio/
CSV_FILE_ESC50: /home/benjamin.cretois/data/esc50/ESC-50-master/meta/esc50.csv
MINI_ESC50_PATH: /home/benjamin.cretois/data/esc50/miniESC50/
